#!/bin/bash

showHelp() {
    cat<< EOF

    ____  __  ___   __
   / __ \/ / / / | / /
  / /_/ / / / /  |/ /
 / _, _/ /_/ / /|  /
/_/ |_|\____/_/ |_/
node script runner

RUN is a script runner build for Node.js written in BASH.

Usage:
    run [options] <Script> [subScript]

Options:
    -h, --help      show brief help
    -d,--develop    run in development mode

Examples:
    run start server
    run -d start client
    run test

EOF

    if [ "$1" ]; then
        logError "$1"
        exit 1
    fi
    exit 0
}
